fix(outdoor_sensor_node): add missing CONFIG_ZBUS_RUNTIME_OBSERVERS
The bme680_sensor library uses zbus_chan_add_obs() to subscribe to
the trigger channel at init time. This function requires
CONFIG_ZBUS_RUNTIME_OBSERVERS=y, which was present in gateway and
sensor-node prj.conf but missing from outdoor_sensor_node.

Fixes CI build failure:
  error: implicit declaration of function 'zbus_chan_add_obs'